config/routes.rb
Pinboard::Application.routes.draw do

  resources :pins

  root "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :set_pin, only: [:show, :edit, :update, :destroy]

	def index
	end

	def show
	end

	def new
		@pin = Pin.new
	end

	def create
		@pin = Pin.new(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Successfully created new Pin"
		else
			 render action 'new'
		end
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description)
	end

	def set_pin
      @pin = Pin.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
  	<div>
  		PINBOARD
  	</div>
  </header>

	

</body>
</html>

<% flash.each do |name, msg| %>
	<%= content_tag :di, msg, class: "alert alert-info" %>
<% end %>

<%= yield %>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>


<div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , class:"form-control"%>
  </div>

<div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description , class:"form-control"%>
  </div>
  <div class="actions form-group">
    <%= f.submit  class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pins/index.html.erb
<h1>This is the index placeholder</h1>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<h1><%= @pin.title %> </h1>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>